uavcan.node.id   :        ["Integer",  "PARAM_NODE_ID",           "mutable",   50,  0,  256]
system.name :             ["String",   "PARAM_NODE_NAME",         "mutable",   ""]
uavcan.node.description : ["String",   "PARAM_NODE_DESCRIPTION",  "mutable",   ""]
