uavcan.node.id:
  type: Integer
  enum: PARAM_NODE_ID
  flags: mutable
  default: 50
  min: 0
  max: 256

system.name:
  type: String
  enum: PARAM_NODE_NAME
  flags: mutable
  default: ""

uavcan.node.description:
  type: String
  enum: PARAM_NODE_DESCRIPTION
  flags: mutable
  default: ""
