name: build

on: [push]
jobs:
  build:
    strategy:
      matrix:
        target: [ubuntu_minimal, ubuntu_publisher_example]
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Checkout libparams
        uses: actions/checkout@v3
        with:
          repository: PonomarevDA/libparams
          path: Libs/libparams
          ref: v0.8.4

      - name: Install dependencies
        run: |
          sudo apt-get install -y make gcc-arm-none-eabi
          pip install -U nunavut

      - run: make -s generage_dsdl
      - run: make -s ${{ matrix.target }}
