name: build

on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Install GIT
        run: sudo apt-get update && sudo apt-get install -y git

      - uses: actions/checkout@v3
        with:
          path: 'repository'
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get install -y make gcc-arm-none-eabi
          pip install -U nunavut

      - name: Install gtest
        run: |
          sudo apt-get install libgtest-dev cmake                                   &&  \
          cd /usr/src/gtest                                                         &&  \
          sudo cmake CMakeLists.txt                                                 &&  \
          sudo make                                                                 &&  \
          sudo cp ./lib/libgtest*.a /usr/lib

      - run: ./repository/scripts/nnvg_generate_c_headers.sh
      - run: cd repository/tests/ubuntu && make -s build
